using MpctTramites.Api.Domain;
namespace MpctTramites.Api.Contracts;
public record LoginRequest(string Email, string Password);
public record RegistroRequest(string Email, string Password, string Nombres, string Apellidos);
public record CrearSolicitudRequest(string Ruc, TipoSolicitud Tipo, string RepresentanteNombre, string RepresentanteDocumento, string RepresentanteEmail, string Rubro, string Actividad, decimal AreaMetrosCuadrados, string DireccionLocal);
public record SeguimientoRequest(string Ruc);
public record AbrirCajaRequest(decimal MontoInicial);
public record PagoPresencialRequest(Guid SolicitudId, MedioPago Medio, decimal Monto);
public record CerrarCajaRequest(decimal TotalDeclarado);
public record ResultadoInspeccionRequest(string Estado, string? Observaciones, string RespuestasJson, decimal? Latitud, decimal? Longitud, bool Firmar);
public record CrearPersonalRequest(string Email, string Password, string Nombres, string Apellidos, string Rol);
public record CambiarEstadoUsuarioRequest(bool Activo, string? Motivo);
public record RestablecerPasswordRequest(string PasswordNueva);
public record RevisarPagoRequest(bool Aprobado, string? Motivo);
public record ActualizarPerfilRequest(string Email, string Nombres, string Apellidos, string PasswordActual, string? PasswordNueva);
